### ISSUE TITLE
Redirection to pypi slow?

### ISSUE THREAD

**Issue by duedal** [stevearc/pypicloud#122] opened 2017-04-28 09:29 UTC
When pypicloud redirects it adds a 600-700ms delay. If you have a lot of deps this will really add up.

Expected
```
time curl -s "https://pypi.python.org/pypi/flask-sqlalchemy"
        0.09 real         0.01 user         0.00 sys
```

Actual result
```
time curl -s "https://pypi.stevearc.com/pypi/flask-sqlalchemy" > /dev/null
        0.72 real         0.01 user         0.01 sys
```

This is regardless of correct caching set up.

Having it fallback to a cache does not improve things.
```
pypi.always_show_upstream = false
pypi.fallback = cache
```

**Comment by brunsgaard** [comment] 2017-04-28 10:28
@duedal Yeah, this is quite annoying.

I cloned the repo and tried to reproduce from master, I dont see the issue in my virtual env on a fresh install. But we are experiencing the same thing as you in our production.

Clearly something is not as it should be.

**Comment by duedal** [comment] 2017-04-28 12:50
You can mitigate this by adding caching to nginx or whatever you have in front of devpi, like so
```
uwsgi_cache_use_stale updating;
uwsgi_no_cache $http_status 200;
uwsgi_cache_valid 302 2d;
```

**Comment by stevearc** [comment] 2017-05-01 07:01
Huh...I'm having the same problem as @brunsgaard reproducing the issue locally. I'll need some more information to find the root issue. Any of the following would be helpful:
* pypicloud version
* what cache backend you're using
* uwsgi or other wsgi server settings

Additionally, the delay you see when you're testing `pypi.stevearc.com` against `pypi.python.org` might just be because my demo server is a cheap Digital Ocean droplet hosted in SF. If you're not on the west coast that could account for some of it. FWIW when I test it I don't see it add any noticeable latency.

**Comment by stevearc** [comment] 2020-11-17 05:54
Revisiting this again, I wonder if it could have been for the same reasons as #115 

Closing due to lack of repro. If anyone runs into this again feel free to reopen

**Closed by stevearc** 2020-11-17 05:54 UTC
