### ISSUE TITLE
User deletion fails when there are groups attached

### ISSUE THREAD

**Issue by underyx** [stevearc/pypicloud#150] opened 2018-01-04 14:41 UTC
```
04/01/2018 14:11:51  File "/usr/local/site-packages/pypicloud/views/admin.py", line 49, in delete_user
04/01/2018 14:11:51    self.request.access.delete_user(username)
04/01/2018 14:11:51  File "/usr/local/site-packages/pypicloud/access/sql.py", line 262, in delete_user
04/01/2018 14:11:51    self.db.query(User).filter_by(username=username).delete()
04/01/2018 14:11:51  File "/usr/local/site-packages/sqlalchemy/orm/query.py", line 3236, in delete
04/01/2018 14:11:51    delete_op.exec_()
04/01/2018 14:11:51  File "/usr/local/site-packages/sqlalchemy/orm/persistence.py", line 1325, in exec_
04/01/2018 14:11:51    self._do_exec()
04/01/2018 14:11:51  File "/usr/local/site-packages/sqlalchemy/orm/persistence.py", line 1517, in _do_exec
04/01/2018 14:11:51    self._execute_stmt(delete_stmt)
04/01/2018 14:11:51  File "/usr/local/site-packages/sqlalchemy/orm/persistence.py", line 1332, in _execute_stmt
04/01/2018 14:11:51    mapper=self.mapper)
04/01/2018 14:11:51  File "/usr/local/site-packages/sqlalchemy/orm/session.py", line 1170, in execute
04/01/2018 14:11:51    bind, close_with_result=True).execute(clause, params or {})
04/01/2018 14:11:51  File "/usr/local/site-packages/sqlalchemy/engine/base.py", line 948, in execute
04/01/2018 14:11:51    return meth(self, multiparams, params)
04/01/2018 14:11:51  File "/usr/local/site-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
04/01/2018 14:11:51    return connection._execute_clauseelement(self, multiparams, params)
04/01/2018 14:11:51  File "/usr/local/site-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
04/01/2018 14:11:51    compiled_sql, distilled_params
04/01/2018 14:11:51  File "/usr/local/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
04/01/2018 14:11:51    context)
04/01/2018 14:11:51  File "/usr/local/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
04/01/2018 14:11:51    exc_info
04/01/2018 14:11:51  File "/usr/local/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
04/01/2018 14:11:51    reraise(type(exception), exception, tb=exc_tb, cause=cause)
04/01/2018 14:11:51  File "/usr/local/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
04/01/2018 14:11:51    raise value.with_traceback(tb)
04/01/2018 14:11:51  File "/usr/local/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
04/01/2018 14:11:51    context)
04/01/2018 14:11:51  File "/usr/local/site-packages/sqlalchemy/engine/default.py", line 507, in do_execute
04/01/2018 14:11:51    cursor.execute(statement, parameters)
04/01/2018 14:11:51  File "/usr/local/site-packages/psycopg2cffi/_impl/cursor.py", line 30, in check_closed_
04/01/2018 14:11:51    return func(self, *args, **kwargs)
04/01/2018 14:11:51  File "/usr/local/site-packages/psycopg2cffi/_impl/cursor.py", line 263, in execute
04/01/2018 14:11:51    self._pq_execute(self._query, conn._async)
04/01/2018 14:11:51  File "/usr/local/site-packages/psycopg2cffi/_impl/cursor.py", line 696, in _pq_execute
04/01/2018 14:11:51    self._pq_fetch()
04/01/2018 14:11:51  File "/usr/local/site-packages/psycopg2cffi/_impl/cursor.py", line 757, in _pq_fetch
04/01/2018 14:11:51    raise self._conn._create_exception(cursor=self)
04/01/2018 14:11:51sqlalchemy.exc.IntegrityError: (psycopg2cffi._impl.exceptions.IntegrityError) update or delete on table "pypicloud_users" violates foreign key constraint "pypicloud_user_groups_username_fkey" on table "pypicloud_user_groups"
04/01/2018 14:11:51DETAIL:  Key (username)=(foobar) is still referenced from table "pypicloud_user_groups".
04/01/2018 14:11:51 [SQL: 'DELETE FROM pypicloud_users WHERE pypicloud_users.username = %(username_1)s'] [parameters: {'username_1': 'foobar'}] (Background on this error at: http://sqlalche.me/e/gkpj)
```

**Comment by stevearc** [comment] 2018-01-07 04:41
I'm having trouble reproducing this. Could you give me detailed steps (including version of postgres) or a failing test? The [test_delete_user](https://github.com/stevearc/pypicloud/blob/c1458a8ace71cd628b7062d0fc403070a62399ea/tests/test_access_backends.py#L842-L854) test should already be catching this if it fails, which make me think there's either more involved in the repro or it only fails for certain versions of Postgres/SQLAlchemy

**Comment by underyx** [comment] 2018-01-08 14:59
Using PostgreSQL 9.5.4, Running on the `pypy:3-5.9-slim` Docker image. The dependency versions we're using are:

```
beaker==1.9.0             # via pyramid-beaker
boto3==1.4.8              # via pypicloud
botocore==1.8.12          # via boto3, dynamo3, s3transfer
cffi==1.11.2              # via psycopg2cffi
distlib==0.2.5            # via pypicloud
docutils==0.14            # via botocore
dynamo3==0.4.10
flywheel==0.5.2
gevent==1.2.2
greenlet==0.4.12          # via gevent
gunicorn==19.7.1
hupper==1.0               # via pyramid
jinja2==2.10              # via pyramid-jinja2
jmespath==0.9.3           # via boto3, botocore
markupsafe==1.0           # via jinja2, pyramid-jinja2
passlib==1.7.1            # via pypicloud
paste==2.0.3              # via pypicloud
pastedeploy==1.5.2        # via plaster-pastedeploy, pyramid
plaster-pastedeploy==0.4.2  # via pyramid
plaster==1.0              # via plaster-pastedeploy, pyramid
psycopg2cffi==2.7.7
pyasn1==0.4.2             # via rsa
pycparser==2.18           # via cffi
pycrypto==2.6.1           # via pypicloud
pypicloud==1.0.1
pyramid-beaker==0.8       # via pypicloud
pyramid-duh==0.1.2        # via pypicloud
pyramid-jinja2==2.7       # via pypicloud
pyramid-rpc==0.8          # via pypicloud
pyramid-tm==2.2           # via pypicloud
pyramid==1.9.1            # via pypicloud, pyramid-beaker, pyramid-duh, pyramid-jinja2, pyramid-rpc, pyramid-tm
python-dateutil==2.6.1    # via botocore
repoze.lru==0.7           # via pyramid
rsa==3.4.2                # via pypicloud
s3transfer==0.1.12        # via boto3
six==1.11.0               # via dynamo3, flywheel, paste, psycopg2cffi, pypicloud, pyramid-duh, python-dateutil
sqlalchemy==1.1.15        # via zope.sqlalchemy
transaction==2.1.2        # via pypicloud, pyramid-tm, zope.sqlalchemy
translationstring==1.3    # via pyramid
venusian==1.1.0           # via pyramid, pyramid-rpc
webob==1.7.4              # via pyramid
zope.deprecation==4.3.0   # via pyramid, pyramid-jinja2
zope.interface==4.4.3     # via pyramid, transaction, zope.sqlalchemy
zope.sqlalchemy==0.7.7    # via pypicloud
```

**Comment by stevearc** [comment] 2018-01-15 05:07
I believe I have a fix for this, but I never was able to exactly reproduce the error you were getting. It looks like your failure was due to a Foreign Key constraint on the groups table, but that had already been configured to cascade on deletes. I was able to find an error when the user had been granted specific permissions on a package, and I fixed that. I have a few more things I want to get in and then I'll cut a new release. If you're at all concerned that this hasn't fixed your error you can check the new version and get back to me.

**Closed** 2018-01-26 08:37 UTC
