### ISSUE TITLE
S3 Package Uploads / Downloads are corrupted

### ISSUE THREAD

**Issue by vjm** [stevearc/pypicloud#221] opened 2019-10-24 11:13 UTC
- Description: When uploading source distribution packages (eg `tar.gz`, `zip`), they seem to upload fine but are corrupted in reality.
- Possible Issue: I think that this is due to the way that the boto client is being used to upload files, but am not sure.
- Environment: S3 Storage, Dynamo Cache, Deployed using Serverless Framework / Lambda, `serverless-wsgi` plugin
- Note: The packages I am generating work locally to install before upload, and I am able to successfully download and install if I directly upload the package to S3 after the original package upload through `twine`, which makes me confident it must be related to the upload process.

Any thoughts?

**Comment by vjm** [comment] 2019-10-24 13:43
update: I found the issue -- API gateway was refusing those binary data types (`application/zip`, `application/gzip`) -- what is the correct datatype for `whl`?

**Comment by stevearc** [comment] 2019-10-26 18:42
I think that is the correct data type. Wheels are just zipfiles https://www.python.org/dev/peps/pep-0427/

**Comment by stevearc** [comment] 2020-11-17 06:30
Closing as this seems to be caused by the API gateway

**Closed by stevearc** 2020-11-17 06:30 UTC
